class Cap
{
	public static void main(String[] args)
	{   String  water="drink";
        System.out.println(water);
		String  dress="kurtha";
		System.out.println(dress);
		String  show="film";
		System.out.println(show);
		String  phone="smart";
		System.out.println(phone);
		String  table="good";
		System.out.println(table);
		String   Pen="blue";
		System.out.println(Pen);
		String   Pencil="blackcolor";
		System.out.println(Pencil);
		String   Language="kannada";
		System.out.println(Language);
		String   Maths="yes";
		System.out.println(Maths);
		String  Photo="album";
		System.out.println(Photo);
		String  Army="selute";
		System.out.println(Army);
		String  Navy="sea";
		System.out.println(Navy);
		String  Pilot="Aerospace";
		System.out.println(Pilot);
		String  Bus="gov";
		System.out.println(Bus);
		String Driver="car";
		System.out.println(Driver);
		String Tools="box";
        System.out.println(Tools);
		String amazing="incredible";
        System.out.println(amazing);
		String anger="enrage";
        System.out.println(anger);
		String angry="wrathful";
        System.out.println(angry);
		String answer="reply";
        System.out.println(answer);
		String ask="question";
        System.out.println(ask);
		String awful="dreadful";
        System.out.println(awful);
		String bad="depraved";
        System.out.println(bad);
		String beautiful="gorgeous";
        System.out.println(beautiful);
		String begin="start";
        System.out.println(begin);
		String big="enormous";
        System.out.println(big);
		String brave="courageous";
        System.out.println(brave);
		String Break="fracture";
        System.out.println(Break);
		String bright="sparkling";
        System.out.println(bright);
		String calm="quite";
        System.out.println(calm);
		String come="approach";
        System.out.println(come);
		String cool="chilly";
        System.out.println(cool);
		String crooked="bent";
        System.out.println(crooked);
		String cry="weep";
        System.out.println(cry);
		String cut="slice";
        System.out.println(cut);
		String dangerous="perilous";
        System.out.println(dangerous);
		String dark="shadowy";
        System.out.println(dark);
		String decide="determine";
        System.out.println(decide);
		String define="certain";
        System.out.println(define);
		String delicious="savory";
        System.out.println(delicious);
		String describe="portray";
        System.out.println(describe);
		String destroy="ruin";
        System.out.println(destroy);
		String difference="disagreement";
        System.out.println(difference);
		String Do="execute";
        System.out.println(Do);
		String dull="unimaginative";
        System.out.println(dull);
		String eager="keen";
        System.out.println(eager);
		String end="stop";
        System.out.println(end);
		String enjoy="appreciate";
        System.out.println(enjoy);
		String explain="elaborate";
        System.out.println(explain);
		String fair="just";
        System.out.println(fair);
		String fall="drop";
        System.out.println(fall);
		String False="fake";
        System.out.println(False);
		String fast="quick";
        System.out.println(fast);
		String fat="stout";
        System.out.println(fat);
		String fear="fright";
        System.out.println(fear);
		String fly="soar";
        System.out.println(fly);
		String funny="droll";
        System.out.println(funny);
		String get="obtain";
        System.out.println(get);
		String go="depart";
        System.out.println(go);
		String good="apt";
        System.out.println(good);
		String great="noteway";
        System.out.println(great);
		String gross="rude";
        System.out.println(gross);
		String happy="pleased";
        System.out.println(happy);
		String hate="despite";
        System.out.println(hate);
		String have="acquire";
        System.out.println(have);
		String help="aid";
        System.out.println(help);
		String hide="conceal";
        System.out.println(hide);
		String hurry="hasten";
        System.out.println(hurry);
		String hurt="damage";
        System.out.println(hurt);
		String idea="thougt";
        System.out.println(idea);
		String important="vital";
        System.out.println(important);
		String interesting="bright";
        System.out.println(interesting);
		String keep="hold";
        System.out.println(keep);
		String kill="slay";
        System.out.println(kill);
		String lazy="indolent";
        System.out.println(lazy);
		String little="dinky";
        System.out.println(little);
	}
}